<?php
namespace App\Services;
use App\Models\{User,Membership,Role};
use Illuminate\Support\{Str,Facades\DB};
use Illuminate\Validation\ValidationException;
class Directory {
 public function save(array $data,?Membership $member,Access $access):Membership{
  validator($data,['name'=>'required|string|max:160','email'=>'nullable|email|max:254','phone'=>'nullable|string|max:40','password'=>['nullable',\Illuminate\Validation\Rules\Password::min(12)->mixedCase()->numbers()],'role_id'=>'nullable|integer','area_ids'=>'array','area_ids.*'=>'integer'])->validate();$email=isset($data['email'])?Str::lower(trim($data['email'])):null;$email=$email?:null;$login=!empty($data['login_enabled']);$active=!empty($data['active']);if($login&&!$email)throw ValidationException::withMessages(['email'=>'El acceso requiere correo.']);$role=!empty($data['role_id'])?$access->query(Role::class)->findOrFail($data['role_id']):null;if($login&&!$role)throw ValidationException::withMessages(['role_id'=>'El acceso requiere un rol.']);$areaIds=array_values(array_unique(array_map('intval',$data['area_ids']??[])));if(count($areaIds)!==$access->areas()->whereIn('id',$areaIds)->count())abort(422);if($login&&$role?->area_scope&&!$areaIds)throw ValidationException::withMessages(['area_ids'=>'Selecciona al menos un área.']);
  return DB::transaction(function()use($data,$member,$access,$email,$login,$active,$role,$areaIds){$all=$access->query(Membership::class)->lockForUpdate()->get();if($member&&$member->active&&$member->login_enabled&&$member->role?->code==='ORG_ADMIN'&&(!$active||!$login||$role?->code!=='ORG_ADMIN')){if(!$all->contains(fn($m)=>$m->id!==$member->id&&$m->active&&$m->login_enabled&&$m->user->active&&$m->role?->active&&$m->role?->code==='ORG_ADMIN'))throw ValidationException::withMessages(['role_id'=>'Conserva al menos un administrador activo.']);}
   $user=$member?->user;$existing=$email?User::where('email',$email)->first():null;if($user&&$existing&&$existing->id!==$user->id)throw ValidationException::withMessages(['email'=>'Este correo pertenece a otra identidad.']);if(!$member&&$existing){if($all->contains('user_id',$existing->id))throw ValidationException::withMessages(['email'=>'Esta persona ya está en el directorio.']);$user=$existing;$login=false;$role=null;$areaIds=[];}else{if($user&&!$email&&$user->memberships()->where('id','!=',$member->id)->where('login_enabled',true)->exists())throw ValidationException::withMessages(['email'=>'Otra organización requiere este correo para su acceso.']);$user??=new User;$user->fill(['name'=>$data['name'],'email'=>$email,'phone'=>$data['phone']??'','active'=>true]);if(!$user->exists)$user->password=Str::random(64);if(!empty($data['password']))$user->password=$data['password'];$user->save();}
   $member??=new Membership(['organization_id'=>$access->member->organization_id,'user_id'=>$user->id]);$member->fill(['role_id'=>$role?->id,'area_ids'=>$areaIds,'login_enabled'=>$login,'active'=>$active]);$member->save();$access->audit('directory.saved','membership:'.$member->id);return $member;});
 }
}
