# Generated by Django 5.2.17 on 2026-10-01 16:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Congregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nombre")),
                ("slug", models.SlugField(unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "privacy_notice",
                    models.TextField(
                        default="Usaremos tus datos únicamente para orientar y dar seguimiento a tu solicitud de servicio. Contacta a la coordinación para ejercer tus derechos de acceso, rectificación o cancelación.",
                        verbose_name="Aviso de privacidad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("folio", models.CharField(max_length=30, unique=True)),
                ("answers", models.JSONField(default=dict)),
                ("state", models.CharField(max_length=80)),
                (
                    "next_action",
                    models.CharField(max_length=240, verbose_name="Próxima acción"),
                ),
                ("due_at", models.DateTimeField()),
                (
                    "state_entered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("pause_started", models.DateTimeField(blank=True, null=True)),
                ("pause_reason", models.TextField(blank=True)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("integration_role", models.CharField(blank=True, max_length=160)),
                ("integration_date", models.DateField(blank=True, null=True)),
                ("consent_at", models.DateTimeField()),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.application",
                    ),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("filename", models.CharField(max_length=180)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("status", models.CharField(default="complete", max_length=20)),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("action", models.CharField(max_length=80)),
                ("object_type", models.CharField(max_length=80)),
                ("object_id", models.CharField(max_length=80)),
                ("detail", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("file", models.FileField(upload_to="private/%Y/%m")),
                ("original_name", models.CharField(max_length=160)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.application",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("text", models.TextField()),
                ("private", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("scheduled_at", models.DateTimeField(verbose_name="Fecha y hora")),
                (
                    "interviewer",
                    models.CharField(max_length=160, verbose_name="Entrevistador"),
                ),
                (
                    "location",
                    models.CharField(max_length=240, verbose_name="Lugar / enlace"),
                ),
                ("result", models.TextField(blank=True, verbose_name="Resultado")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("completed", "Realizada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.application",
                    ),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key", "created_at"], name="core_logina_key_281959_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("coordinator", "Coordinación"),
                            ("advisor", "Asesor"),
                            ("reader", "Consulta"),
                            ("technical", "Técnico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="responsible",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.membership"
            ),
        ),
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=160, verbose_name="Nombre")),
                ("description", models.TextField(verbose_name="Propósito")),
                ("leader_name", models.CharField(max_length=160, verbose_name="Líder")),
                (
                    "contact",
                    models.CharField(max_length=200, verbose_name="Contacto del líder"),
                ),
                ("requirements", models.TextField(verbose_name="Requisitos mínimos")),
                (
                    "capacity",
                    models.PositiveIntegerField(default=10, verbose_name="Capacidad"),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("text", models.TextField()),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("key", models.CharField(max_length=180, unique=True)),
                (
                    "application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.application",
                    ),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=160, verbose_name="Título")),
                ("slug", models.SlugField(default=uuid.uuid4, unique=True)),
                ("description", models.TextField(verbose_name="Descripción")),
                ("published", models.BooleanField(default=False)),
                (
                    "closes_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Cierre"),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.ministry"
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="application",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.opportunity"
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=160, verbose_name="Nombre")),
                ("email", models.EmailField(max_length=254, verbose_name="Correo")),
                ("phone", models.CharField(max_length=30, verbose_name="Teléfono")),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.person"
            ),
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=160, verbose_name="Nombre")),
                ("version", models.PositiveIntegerField(default=1)),
                ("published", models.BooleanField(default=False)),
                ("questions", models.JSONField(default=list, verbose_name="Preguntas")),
                ("is_test", models.BooleanField(default=False)),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Instrucciones"),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublicTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("instructions", models.TextField(verbose_name="Instrucciones")),
                ("expires_at", models.DateTimeField()),
                ("answers", models.JSONField(default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.application",
                    ),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.questionnaire",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.questionnaire"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.questionnaire"
            ),
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=160, verbose_name="Nombre")),
                ("version", models.PositiveIntegerField(default=1)),
                ("published", models.BooleanField(default=False)),
                (
                    "definition",
                    models.JSONField(default=dict, verbose_name="Definición de flujo"),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.congregation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.workflow"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.workflow"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "congregation"), name="unique_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["congregation", "email"], name="core_person_congreg_51a481_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["congregation", "state"], name="core_applic_congreg_c9aada_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["responsible", "due_at"], name="core_applic_respons_ea5068_idx"
            ),
        ),
    ]
